export const LOCATION_IMAGE_MAP: Record<string, string> = {
  Aguadecoco: "/images/Aguadecoco.webp",
  "Altrimenti Mixology Art": "/images/Altrimenti Mixology Art.webp",
  Anvil: "/images/Anvil.webp",
  Botero: "/images/Botero.webp",
  "BV Rooftop": "/images/BV Rooftop.jpg",
  "Chiosco Mercedes": "/images/Chiosco Mercedes.webp",
  Dabass: "/images/Dabass.webp",
  "Dall'Antiquario": "/images/anticq.jpg",
  "Degustazione ristoro e dispensa": "/images/Degustazione ristoro dispen.webp",
  Eterno: "/images/Eterno.webp",
  "Il Nemico": "/images/Il Nemico.webp",
  "Let It Be": "/images/Let It Be.webp",
  "Madame del Borgo": "/images/MA.DA.ME..webp",
  "Mary's Pub": "/images/Mary's Pub.webp",
  "Minimarket Milan": "/images/Minimarket Milan.jpg",
  "Moon Cafè": "/images/Moon-Cafe.webp",
  Origin: "/images/Origin.webp",
  "Prosciutteria Jesolo": "/images/Prosciutteria.webp",
  Pulp: "/images/pulp.webp",
  "Fiaschetteria Quanto Basta": "/images/Quanto Basta.webp",
  "The First Caffè": "/images/The-First-Caffe.webp",
  "The Manhattan": "/images/The Manhattan.webp",
  "This Agio Cocktail Bar": "/images/This Agio.webp",
  Tipiko: "/images/Tipiko.webp",
  Tosti: "/images/Tosti.webp",
  Verdi: "/images/Verdi.webp",
  "Vinyl Pub": "/images/vinyl.jpg",
  "Violet Hill Cafè": "/images/Violet-Hill-Cafe.webp",
};
