/**
 * Elenco bar / locali dove è disponibile Mundo Gin.
 * Coordinate: punto preciso dell’ingresso sul marciapiede (Google Maps → tasto destro sul pin → lat,lng).
 * Evita il centro strada generico: altrimenti il marker risulta spostato rispetto al locale.
 */
export type Location = {
  id: string;
  name: string;
  address: string;
  city: string;
  cap?: string;
  province?: string;
  lat: number;
  lng: number;
  mapUrl?: string;
  instagramUrl?: string;
};

const LOCATIONS_RAW: Location[] = [
  {
    id: "1",
    name: "Aguadecoco",
    address: "Via Treviglio, 22",
    city: "Brignano Gera d'Adda",
    cap: "24053",
    province: "BG",
    lat: 45.5408516,
    lng: 9.6403046,
    mapUrl: "https://maps.app.goo.gl/KNBjV5cxmtKri4GfA",
    instagramUrl: "https://www.instagram.com/aguadecoco_brignano/",
  },
  {
    id: "2",
    name: "Altrimenti Mixology Art",
    address: "Via Castelfidardo, 6",
    city: "Milano",
    cap: "20121",
    province: "MI",
    lat: 45.4784907,
    lng: 9.1892499,
    mapUrl: "https://maps.app.goo.gl/XTVNMbPogZFMzD7t5",
    instagramUrl: "https://www.instagram.com/altrimentimixologyart/",
  },
  {
    id: "3",
    name: "Anvil",
    address: "Via Giovanni Paolo II, 7",
    city: "Romano di Lombardia",
    cap: "24058",
    province: "BG",
    lat: 45.5240444,
    lng: 9.7502379,
    mapUrl: "https://maps.app.goo.gl/uA4Gj7favz8sxZXg7",
    instagramUrl: "https://www.instagram.com/anvilindustries/",
  },
  {
    id: "4",
    name: "Botero",
    address: "Via Giuseppe Verdi, 7",
    city: "Crema",
    cap: "26013",
    province: "CR",
    lat: 45.363117,
    lng: 9.6836126,
    mapUrl: "https://maps.app.goo.gl/nJwKDpSJtC4YY5Df7",
    instagramUrl: "https://www.instagram.com/ristobotero/",
  },
  {
    id: "5",
    name: "Chiosco Mercedes",
    address: "Via Giacomo Zanella, 2 bis",
    city: "Lido di Jesolo",
    cap: "30016",
    province: "VE",
    lat: 45.4952262,
    lng: 12.6152449,
    mapUrl: "https://maps.app.goo.gl/5NnUYmXqte5XuxDG7",
    instagramUrl: "https://www.instagram.com/chioscomercedesofficial/",
  },
  {
    id: "6",
    name: "Dabass",
    address: "Via Piacenza, 13",
    city: "Milano",
    cap: "20135",
    province: "MI",
    lat: 45.4528,
    lng: 9.2072,
    mapUrl: "https://maps.app.goo.gl/SJxRznTEwsS2ySsm6",
    instagramUrl: "https://www.instagram.com/dabassmilano/",
  },
  {
    id: "7",
    name: "Degustazione ristoro e dispensa",
    address: "Via Tommaso da Cazzaniga, Corso Garibaldi, 89/A",
    city: "Milano",
    cap: "20121",
    province: "MI",
    lat: 45.4766585,
    lng: 9.1833827,
    mapUrl: "https://maps.app.goo.gl/6hnbkRZWzQqh6RHn8",
    instagramUrl: "https://www.instagram.com/degustazioneristorodispensa/",
  },
  {
    id: "8",
    name: "Eterno",
    address: "Viale Campania, 30",
    city: "Milano",
    cap: "20133",
    province: "MI",
    lat: 45.4651046,
    lng: 9.2241911,
    mapUrl: "https://maps.app.goo.gl/5ZKpkx9TQxdeKFyJA",
    instagramUrl: "https://www.instagram.com/eterno_milano/",
  },
  {
    id: "9",
    name: "Il Nemico",
    address: "Via Piacenza, 20",
    city: "Milano",
    cap: "20135",
    province: "MI",
    lat: 45.4492969,
    lng: 9.2051671,
    mapUrl: "https://maps.app.goo.gl/i1UPN4rfmF4UPMjR9",
    instagramUrl: "https://www.instagram.com/il_nemico_milano/",
  },
  {
    id: "10",
    name: "Let It Be",
    address: "Via Polidoro Caldara, 27",
    city: "Caravaggio",
    cap: "24043",
    province: "BG",
    lat: 45.4978765,
    lng: 9.6425237,
    mapUrl: "https://maps.app.goo.gl/UcPvuijtcPTxn5W16",
    instagramUrl: "https://www.instagram.com/letitbe_caravaggio/",
  },
  {
    id: "11",
    name: "Madame del Borgo",
    address: "Viale Tiberio, 14",
    city: "Rimini",
    cap: "47921",
    province: "RN",
    lat: 44.0648422,
    lng: 12.5619899,
    mapUrl: "https://maps.app.goo.gl/hyjHnmxE1G2ePsYH8",
    instagramUrl: "https://www.instagram.com/madame.delborgo/",
  },
  {
    id: "12",
    name: "Mary's Pub",
    address: "Via Bafile, 546",
    city: "Jesolo",
    cap: "30016",
    province: "VE",
    lat: 45.497812,
    lng: 12.6220619,
    mapUrl: "https://maps.app.goo.gl/UJf68JgaYaToPwKe6",
    instagramUrl: "https://www.instagram.com/marys_pub/",
  },
  {
    id: "14",
    name: "Moon Cafè",
    address: "Piazza Castello, 17",
    city: "Castel Rozzone",
    cap: "24040",
    province: "BG",
    lat: 45.555149,
    lng: 9.6239784,
    mapUrl: "https://maps.app.goo.gl/Pvr193sA6nMK1c7L7",
    instagramUrl: "https://www.instagram.com/mooncafe8/",
  },
  {
    id: "15",
    name: "Origin",
    address: "Via Bergamo, 15",
    city: "Monza",
    cap: "20900",
    province: "MB",
    lat: 45.5836704,
    lng: 9.2842139,
    mapUrl: "https://maps.app.goo.gl/PdJTwGURpZdgSUgQA",
    instagramUrl: "https://www.instagram.com/origin_monza/",
  },
  {
    id: "16",
    name: "Prosciutteria Jesolo",
    address: "Via Andrea Bafile, 421",
    city: "Lido di Jesolo",
    cap: "30016",
    province: "VE",
    lat: 45.4970839,
    lng: 12.6198753,
    mapUrl: "https://maps.app.goo.gl/kwbeMtysMXXcvAaX8",
    instagramUrl: "https://www.instagram.com/prosciutteriajesolo/",
  },
  {
    id: "17",
    name: "Pulp",
    address: "Via Cadore, 48",
    city: "Milano",
    cap: "20135",
    province: "MI",
    lat: 45.4560121,
    lng: 9.2110845,
    mapUrl: "https://maps.app.goo.gl/UT4fyzLzyQKATxA76",
    instagramUrl: "https://www.instagram.com/pulp_milano/",
  },
  {
    id: "18",
    name: "Fiaschetteria Quanto Basta",
    address: "Piazza Vittorio Emanuele II, 25",
    city: "Rivolta d'Adda",
    cap: "26027",
    province: "CR",
    lat: 45.4707675,
    lng: 9.5125964,
    mapUrl: "https://maps.app.goo.gl/hvVK1u3tsepBR5Q69",
    instagramUrl: "https://www.instagram.com/q.b.quantobasta/",
  },
  {
    id: "20",
    name: "The First Caffè",
    address: "Via Mons.E.Bignamini, 1",
    city: "Treviglio",
    cap: "24047",
    province: "BG",
    lat: 45.53055,
    lng: 9.58685,
    mapUrl: "https://maps.app.goo.gl/ApybeAEw1e3i7v7B9",
    instagramUrl: "https://www.instagram.com/thefirstcaffe/",
  },
  {
    id: "21",
    name: "The Manhattan",
    address: "Via Alessandro Volta, 4",
    city: "Milano",
    cap: "20121",
    province: "MI",
    lat: 45.4790873,
    lng: 9.1841339,
    mapUrl: "https://maps.app.goo.gl/XFBn74JfmsMYNKDB8",
    instagramUrl: "https://www.instagram.com/themanhattanmilano/?hl=it",
  },
  {
    id: "22",
    name: "This Agio Cocktail Bar",
    address: "P.za Ippolito Ragghianti, 14",
    city: "Viareggio",
    cap: "55049",
    province: "LU",
    lat: 43.8669336,
    lng: 10.2539275,
    mapUrl: "https://maps.app.goo.gl/GFwVugCJhVWZFg6TA",
    instagramUrl: "https://www.instagram.com/this.agiococktailbar/",
  },
  {
    id: "23",
    name: "Tipiko",
    address: "Via Alessandro Manzoni, 13",
    city: "Castel Rozzone",
    cap: "24040",
    province: "BG",
    lat: 45.5581444,
    lng: 9.6226397,
    mapUrl: "https://maps.app.goo.gl/W7J67J2H1yHoYqJr9",
    instagramUrl: "https://www.instagram.com/tipiko_restaurant/",
  },
  {
    id: "24",
    name: "Tosti",
    address: "Via Silvio Trentin, 1",
    city: "Lido di Jesolo",
    cap: "30016",
    province: "VE",
    lat: 45.4952836,
    lng: 12.6153246,
    mapUrl: "https://maps.app.goo.gl/yq4jNX2kdRsX1FSS6",
    instagramUrl: "https://www.instagram.com/tosti.jesolo/",
  },
  {
    id: "25",
    name: "Dall'Antiquario",
    address: "Via Milano, 30",
    city: "Treviglio",
    cap: "24047",
    province: "BG",
    lat: 45.5235979,
    lng: 9.5588406,
    mapUrl: "https://maps.app.goo.gl/SXDbQiMMHmEaAYfe8",
    instagramUrl: "https://www.instagram.com/dall_antiquario/",
  },
  {
    id: "26",
    name: "Verdi",
    address: "Via Giuseppe Verdi, 18",
    city: "Lido di Jesolo",
    cap: "30016",
    province: "VE",
    lat: 45.5068,
    lng: 12.6458,
    mapUrl: "https://maps.app.goo.gl/GWuPScooA3NoqaMo8",
    instagramUrl: "https://www.instagram.com/verdijesolo/",
  },
  {
    id: "27",
    name: "Violet Hill Cafè",
    address: "Viale Cristoforo Colombo, 103",
    city: "Lido di Camaiore",
    cap: "55041",
    province: "LU",
    lat: 43.8889972,
    lng: 10.2300858,
    mapUrl: "https://maps.app.goo.gl/TvyC2wZagLA1FJSQ8",
    instagramUrl: "https://www.instagram.com/violethill_cafe/",
  },
  {
    id: "28",
    name: "BV Rooftop",
    address: "Via Provinciale per Verdello, 9",
    city: "Brignano Gera d'Adda",
    cap: "24053",
    province: "BG",
    lat: 45.5412162,
    lng: 9.640788,
    mapUrl: "https://maps.app.goo.gl/cY1Rc7rWD2ve6DLa8",
    instagramUrl: "https://www.instagram.com/bv_rooftop/",
  },
  {
    id: "29",
    name: "Vinyl Pub",
    address: "Piazzale Carlo Archinto",
    city: "Milano",
    cap: "20159",
    province: "MI",
    lat: 45.487028,
    lng: 9.184514,
    mapUrl: "https://maps.app.goo.gl/NPfJ7vtSiJZAqKjb6",
    instagramUrl: "https://www.instagram.com/vinylpubmilano/tagged/",
  },
];

export const LOCATIONS = [...LOCATIONS_RAW].sort((a, b) =>
  a.name.localeCompare(b.name, "it")
);
